### ISSUE TITLE
Feature modules integration

### ISSUE THREAD

**Issue by felipehjcosta** [vanniktech/gradle-android-junit-jacoco-plugin#115]
Hi, 

I'm migrating a pet project from a single module to multi modules (and instant app in the future) and I need JaCoCo integration. So, I tryied the snapshot version (0.12.0-SNAPSHOT) in the project but the following exception was thrown when running any command of Gradle:

```
Caused by: groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.all() is applicable for argument types: (com.vanniktech.android.junit.jacoco.GenerationPlugin$_addJacocoAndroid_closure7) values: [com.vanniktech.android.junit.jacoco.GenerationPlugin$_addJacocoAndroid_closure7@697ddda9]
Possible solutions: any(), tail(), tail(), last(), last(), add(java.lang.Object)
        at com.vanniktech.android.junit.jacoco.GenerationPlugin.addJacocoAndroid(GenerationPlugin.groovy:127)
        at com.vanniktech.android.junit.jacoco.GenerationPlugin.addJacoco(GenerationPlugin.groovy:48)
        at com.vanniktech.android.junit.jacoco.GenerationPlugin.addJacoco(GenerationPlugin.groovy:41)
        at com.vanniktech.android.junit.jacoco.GenerationPlugin$_apply_closure2.doCall(GenerationPlugin.groovy:35)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy24.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
```

Thanks

**Comment by vanniktech** [comment]
Which version of AGP and Gradle are you using?

**Comment by vanniktech** [comment]
Interesting, in which module is this causing an exception?

**Comment by felipehjcosta** [comment]
I created a separated branch for this issue:

https://github.com/felipehjcosta/kotlin-rxjava-android/tree/feature/GenerateCodeCoverageFromMultiModules

I'm using it in two feature modules: `base` and `detail`.

**Comment by vanniktech** [comment]
Sorry I somehow missed this. Can you try the latest snapshot?

There is some code to make it work with instant app modules:

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/902f9785b6efd8e6823869be84aca3e60264d00e/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L47

**Comment by felipehjcosta** [comment]
I tried here, but it didn't work. It seems the latest snapshot hasn't changed since Apr 02 or I'm doing something wrong... 🤔  

![image](https://user-images.githubusercontent.com/2865924/40119096-18c85ddc-58f2-11e8-9e83-7cede86acb11.png)
