### ISSUE TITLE
Error groovy.lang.MissingPropertyException: Could not get unknown property 'xml'

### ISSUE THREAD

**Issue by ixsans** [vanniktech/gradle-android-junit-jacoco-plugin#218]
Hi there, I'm trying to integrate jacoco into my Android Studio project and getting this error during gradle sync:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'xml' for extension 'junitJacoco' of type com.vanniktech.android.junit.jacoco.JunitJacocoExtension.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:130)
	at build_44urd2oums4mcm7e9okqxb6qx$_run_closure2.doCall
```

This error due to xml/csv/html part in this config:

```
junitJacoco {
    jacocoVersion = '0.8.7' // type String
    ignoreProjects = [] // type String array
    excludes // type String List
    includeNoLocationClasses = false // type boolean
    includeInstrumentationCoverageInMergedReport = false // type boolean
    xml.enabled = true
    csv.enabled = true
    html.enabled = true
}
```

Note:
I'm using gradle 7.4 and jdk 11

**Comment by davinncia** [comment]
Same issue for me, any luck ?

**Comment by CyxouD** [comment]
Same issue. I've just removed this option

**Comment by syrinx2012** [comment]
Same problem here...
